added AdminPages & filtering options
CS-Social-Good-CalPoly/Vera pull request #251
Opened 2024-02-11 22:43 UTC by Parshana007

2024-02-13 22:50 UTC, daiwik-swaminathan commented on backend/routes/stories.js
> +// Web scraping route
Why was this endpoint added? It seems to not be used/called anywhere...?

2024-02-13 22:51 UTC, daiwik-swaminathan requested changes
Looks good, but please see comment I left on the app.js file in the backend folder

2024-02-13 23:11 UTC, wbrandon25 commented on frontend/src/pages/StoriesPage/StoriesPage.js
> -            <StoryBanner
Restore the removed banner here.

2024-02-13 23:13 UTC, wbrandon25 commented
Great work with the story loading and sorting functionality. For the stories on this page, we want admins to be able to see important info about a story and decide whether they want to approve it or not - the categories won't be needed in this case. For now can you edit the stories list so that for every story we list out the the title, student major, and paragraph text with each story separated by a line break. Don't worry about css or formatting.

2024-02-18 00:40 UTC, wbrandon25 requested changes
The admin page and filtering buttons look great! Take a look at the comment Daiwik made about the webscraping endpoint and my comment on the banner above. Once those are addressed, we should be good to merge!

2024-02-18 23:01 UTC, Parshana007 commented
Sounds good I think the above change was from my last issue and this change I think I accidentally made since AdminPages and StoryPage were so similar. Thanks for the heads up I have fixed those two problems.

2024-02-21 19:43 UTC, daiwik-swaminathan commented
I believe Brandon's request has been successfully addressed. However, the change I requested seems to not be addressed. Specifically, I do not see why the code in backend/routes/stories.js from lines 70-90 is there. If you could explain why this endpoint was added that would be great, otherwise it should be removed. Let me know if you have any questions/clarifications!

2024-02-21 22:04 UTC, daiwik-swaminathan approved these changes
Nice job!

2024-02-22 05:21 UTC, merged